### ISSUE TITLE
Deprecation warnings about ariaExpanded

### ISSUE THREAD

**Issue by omghax** [IvyApp/ivy-tree#5]
As of 9c4f1e1f725aa7135e34c8a2b171d2826ad8697d, I am seeing the following deprecation warning in the console:

```
DEPRECATION: You modified ariaExpanded twice in a single render. This was unreliable in Ember 1.x and will be removed in Ember 3.0 [deprecation id: ember-views.render-double-modify]
```

Seemingly, adding `hasChildren` as a dependent key to `ariaExpanded` causes the property to be recomputed twice. I _think_ what's happening is that the parent node is being rendered first, at which point it has no children, so `ariaExpanded` returns null. Then, as Ember continues rendering, its children are rendered, causing `ariaExpanded` to be re-evaluated.

**Comment by nbibler** [comment]
For the `0.1.x` branch, this was "fixed" with #7.
